# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180610_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高效'), ('gr', '个人')], default='pxjg', max_length=10, verbose_name='结构分类'),
        ),
    ]
