# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180620_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
