# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, default='media/org/2016/11/default-org.jpg', null=True, upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
