# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180625_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='org/default-org.jpg', upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
