# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20180625_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='speciality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='特长'),
        ),
    ]
