# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20180625_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
