# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_courseorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[(0, '后端开发'), (1, 'Web前端开发'), (2, '数据库设计')], default=0, max_length=20),
        ),
    ]
