# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180623_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='课程标签'),
        ),
    ]
