# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', verbose_name='视频访问地址'),
        ),
    ]
