# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='howlong',
            field=models.IntegerField(default=0, verbose_name='视频时长（分）'),
        ),
    ]
