# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '机构'), (3, '教师')], verbose_name='收藏类型'),
        ),
    ]
