# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180622_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='is_read',
            new_name='has_read',
        ),
    ]
