# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='bannerimage/%Y-%m-%d', verbose_name='轮播图片地址')),
                ('imgurl', models.URLField(verbose_name='轮播图跳转URL')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '轮播图表',
                'verbose_name_plural': '轮播图表',
            },
        ),
        migrations.CreateModel(
            name='EmailValiRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.CharField(max_length=50, verbose_name='验证邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], max_length=10, verbose_name='验证类型')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='验证码生成时间')),
            ],
            options={
                'verbose_name': '邮箱验证表',
                'verbose_name_plural': '邮箱验证表',
            },
        ),
    ]
