# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_banner_emailvalirecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='headimg/default.jpg', upload_to='headimg/%Y-%m-%d', verbose_name='上传的图片'),
        ),
    ]
